name: every1minute

on:
  # 定时打卡
  schedule:
    # 下方代码第一段数字表示第 30 分钟，第二段数字表示第 23 小时，但是这个时间比北京时间晚 8 小时，所以当前打卡的时间为 7 点 30 分。
    # 免费版的 Github Action 定时执行会有延迟，大概是延迟半小时到一小时不等。
    - cron: 0 23 * * *
    - cron: 23 0 * * *
    
    
    
env:
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  OPEN_ID: ${{ secrets.OPEN_ID }}
  STUDENT_NUM: ${{ secrets.STUDENT_NUM }}
  ADDRESS: ${{ secrets.ADDRESS }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: yarn
              
            - name: Run Script
              run: node index.js
